"""sync_with_new_schema

Revision ID: 2345fe8c2c28
Revises: 5a6b86c4bd04
Create Date: 2025-08-22 11:30:52.172601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2345fe8c2c28'
down_revision: Union[str, Sequence[str], None] = '5a6b86c4bd04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_attendance_date'), table_name='attendance')
    op.drop_index(op.f('idx_attendance_training_course_id'), table_name='attendance')
    op.drop_index(op.f('idx_attendance_user_id'), table_name='attendance')
    op.drop_index(op.f('idx_issues_created_by_user_id'), table_name='issues')
    op.drop_index(op.f('idx_issues_resolved'), table_name='issues')
    op.drop_index(op.f('idx_issues_training_course_id'), table_name='issues')
    op.drop_index(op.f('idx_notices_created_by_user_id'), table_name='notices')
    op.drop_index(op.f('idx_notices_is_deleted'), table_name='notices')
    op.drop_index(op.f('idx_notices_is_pinned'), table_name='notices')
    op.drop_index(op.f('idx_task_checklist_training_course_id'), table_name='task_checklist')
    op.drop_index(op.f('idx_task_checklist_user_id'), table_name='task_checklist')
    op.alter_column('task_items', 'required_skills',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)
    op.drop_index(op.f('idx_unchecked_descriptions_resolved'), table_name='unchecked_descriptions')
    op.drop_index(op.f('idx_unchecked_descriptions_training_course_id'), table_name='unchecked_descriptions')
    op.drop_index(op.f('idx_unchecked_descriptions_user_id'), table_name='unchecked_descriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_unchecked_descriptions_user_id'), 'unchecked_descriptions', ['user_id'], unique=False)
    op.create_index(op.f('idx_unchecked_descriptions_training_course_id'), 'unchecked_descriptions', ['training_course_id'], unique=False)
    op.create_index(op.f('idx_unchecked_descriptions_resolved'), 'unchecked_descriptions', ['resolved'], unique=False)
    op.alter_column('task_items', 'required_skills',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.create_index(op.f('idx_task_checklist_user_id'), 'task_checklist', ['user_id'], unique=False)
    op.create_index(op.f('idx_task_checklist_training_course_id'), 'task_checklist', ['training_course_id'], unique=False)
    op.create_index(op.f('idx_notices_is_pinned'), 'notices', ['is_pinned'], unique=False)
    op.create_index(op.f('idx_notices_is_deleted'), 'notices', ['is_deleted'], unique=False)
    op.create_index(op.f('idx_notices_created_by_user_id'), 'notices', ['created_by_user_id'], unique=False)
    op.create_index(op.f('idx_issues_training_course_id'), 'issues', ['training_course_id'], unique=False)
    op.create_index(op.f('idx_issues_resolved'), 'issues', ['resolved'], unique=False)
    op.create_index(op.f('idx_issues_created_by_user_id'), 'issues', ['created_by_user_id'], unique=False)
    op.create_index(op.f('idx_attendance_user_id'), 'attendance', ['user_id'], unique=False)
    op.create_index(op.f('idx_attendance_training_course_id'), 'attendance', ['training_course_id'], unique=False)
    op.create_index(op.f('idx_attendance_date'), 'attendance', ['date'], unique=False)
    # ### end Alembic commands ###
